-- ════════════════════════════════════════════════════════════════════════════
-- Migration 037: Merchant Ledger (Phase 1 of Fintech Reconciliation System)
--
-- Append-only, immutable, balance-after ledger that records EVERY money
-- movement for a merchant. Sits IN PARALLEL with the existing
-- journal_entries / journal_lines double-entry GL — does NOT replace it.
-- New money-movement code paths can opt in via fn_post_merchant_ledger_entry();
-- existing journal-only code paths continue unchanged.
--
--   * Partition-ready: RANGE PARTITIONED BY (created_at), monthly.
--     Default partition catches anything outside the seeded range so the
--     table is safe to use immediately even if no monthly partitions exist.
--   * Race-safe: per-(merchant_id, currency) row lock on
--     merchant_ledger_balance_locks, taken inside fn_post_merchant_ledger_entry,
--     guarantees serialised balance_after computation under concurrency.
--   * Idempotent: unique partial index on (merchant_id, idempotency_key).
--     Re-posting with the same key returns the existing entry instead of
--     creating a duplicate.
--   * Immutable: BEFORE UPDATE OR DELETE triggers raise. The only legitimate
--     way to "correct" a ledger entry is to post a reversing entry that
--     references the original via metadata.reverses_id.
--
-- Backfill of historical money movements is intentionally OUT OF SCOPE for
-- this migration; the runner script (_run_migration_037.py) optionally
-- seeds an `opening_balance` entry per restaurant from the live wallet
-- snapshot.
-- ════════════════════════════════════════════════════════════════════════════

BEGIN;

-- ────────────────────────────────────────────────────────────────────────────
-- 1. Transaction-type enum
-- ────────────────────────────────────────────────────────────────────────────
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'merchant_ledger_txn_type') THEN
        CREATE TYPE merchant_ledger_txn_type AS ENUM (
            'opening_balance',
            'payment_received',
            'settlement_initiated',
            'settlement_completed',
            'settlement_reversed',
            'fee_deduction',
            'gst_deduction',
            'refund',
            'chargeback',
            'payout_failure',
            'adjustment',
            'reserve_hold',
            'reserve_release',
            'manual_credit',
            'manual_debit'
        );
    END IF;
END$$;


-- ────────────────────────────────────────────────────────────────────────────
-- 2. Per-(merchant, currency) balance lock table
--
--    Holds the canonical "current running balance" per merchant+currency.
--    fn_post_merchant_ledger_entry locks this row (SELECT ... FOR UPDATE)
--    before reading/writing the ledger so concurrent posters serialise.
--    Updated atomically by the posting function only.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS merchant_ledger_balance_locks (
    merchant_id        UUID            NOT NULL,
    currency           CHAR(3)         NOT NULL DEFAULT 'INR',
    current_balance    NUMERIC(18,4)   NOT NULL DEFAULT 0,
    last_entry_id      UUID,
    last_posted_at     TIMESTAMPTZ,
    version            BIGINT          NOT NULL DEFAULT 0,
    PRIMARY KEY (merchant_id, currency)
);


-- ────────────────────────────────────────────────────────────────────────────
-- 3. Append-only ledger (partitioned by month on created_at)
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS merchant_ledger (
    id                 UUID            NOT NULL DEFAULT gen_random_uuid(),
    merchant_id        UUID            NOT NULL,
    branch_id          UUID,

    -- Stable, human-friendly per-entry reference (e.g. "ML-2026-05-000123").
    -- Generated by the posting function. UNIQUE per merchant.
    ledger_reference   TEXT            NOT NULL,

    transaction_type   merchant_ledger_txn_type NOT NULL,

    -- Exactly one of debit_amount / credit_amount must be > 0.
    -- Both are NUMERIC(18,4) to leave room for fee math without rounding loss;
    -- application code rounds to currency precision on display.
    debit_amount       NUMERIC(18,4)   NOT NULL DEFAULT 0,
    credit_amount      NUMERIC(18,4)   NOT NULL DEFAULT 0,
    balance_after      NUMERIC(18,4)   NOT NULL,
    currency           CHAR(3)         NOT NULL DEFAULT 'INR',

    -- Source linkage (free-form; not all entries have all of these).
    source_type        TEXT,
    source_id          UUID,
    settlement_id      UUID,
    payment_id         UUID,
    order_id           UUID,
    bank_reference     TEXT,
    utr_number         TEXT,

    -- Caller-supplied dedupe key. UNIQUE per merchant when present.
    idempotency_key    TEXT,

    metadata           JSONB           NOT NULL DEFAULT '{}'::jsonb,

    created_at         TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by         UUID,

    -- Composite PK includes the partition key (created_at) — required by
    -- Postgres for partitioned tables.
    CONSTRAINT pk_merchant_ledger PRIMARY KEY (id, created_at),

    CONSTRAINT chk_merchant_ledger_amounts CHECK (
        debit_amount  >= 0
        AND credit_amount >= 0
        AND (debit_amount > 0) <> (credit_amount > 0)   -- exactly one nonzero
    ),
    CONSTRAINT chk_merchant_ledger_currency CHECK (currency = upper(currency))
) PARTITION BY RANGE (created_at);

-- Default partition — catches anything outside seeded monthly partitions
-- so inserts never fail just because nobody created next month's partition.
CREATE TABLE IF NOT EXISTS merchant_ledger_default
    PARTITION OF merchant_ledger DEFAULT;

-- Seed monthly partitions for the current month + next 12 months.
DO $seed$
DECLARE
    start_month DATE := date_trunc('month', now())::date;
    i INT;
    pstart DATE;
    pend   DATE;
    pname  TEXT;
BEGIN
    FOR i IN 0..12 LOOP
        pstart := (start_month + (i || ' months')::interval)::date;
        pend   := (start_month + ((i + 1) || ' months')::interval)::date;
        pname  := format('merchant_ledger_y%sm%s',
                         to_char(pstart, 'YYYY'), to_char(pstart, 'MM'));
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I PARTITION OF merchant_ledger
             FOR VALUES FROM (%L) TO (%L)',
            pname, pstart, pend
        );
    END LOOP;
END
$seed$;

-- ────────────────────────────────────────────────────────────────────────────
-- 4. Indexes (created on the partitioned parent → propagated to all parts)
-- ────────────────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_merchant_ledger_merchant_created
    ON merchant_ledger (merchant_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_merchant_ledger_branch_created
    ON merchant_ledger (branch_id, created_at DESC)
    WHERE branch_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_merchant_ledger_txn_type
    ON merchant_ledger (merchant_id, transaction_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_merchant_ledger_settlement
    ON merchant_ledger (settlement_id)
    WHERE settlement_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_merchant_ledger_payment
    ON merchant_ledger (payment_id)
    WHERE payment_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_merchant_ledger_order
    ON merchant_ledger (order_id)
    WHERE order_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_merchant_ledger_utr
    ON merchant_ledger (utr_number)
    WHERE utr_number IS NOT NULL;

-- NB: Postgres requires unique indexes on a partitioned table to include the
-- partition key (created_at). That would defeat the dedupe semantics, so
-- per-merchant uniqueness for idempotency_key and ledger_reference is
-- enforced via the companion tables below (merchant_ledger_idempotency,
-- merchant_ledger_references). The posting function writes those first,
-- using their PK conflicts as the actual uniqueness contract.
CREATE INDEX IF NOT EXISTS idx_merchant_ledger_idem_lookup
    ON merchant_ledger (merchant_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_merchant_ledger_reference_lookup
    ON merchant_ledger (merchant_id, ledger_reference);

-- Companion uniqueness tables (NOT partitioned).
CREATE TABLE IF NOT EXISTS merchant_ledger_idempotency (
    merchant_id      UUID        NOT NULL,
    idempotency_key  TEXT        NOT NULL,
    ledger_id        UUID        NOT NULL,
    ledger_created_at TIMESTAMPTZ NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (merchant_id, idempotency_key)
);

CREATE TABLE IF NOT EXISTS merchant_ledger_references (
    merchant_id      UUID        NOT NULL,
    ledger_reference TEXT        NOT NULL,
    ledger_id        UUID        NOT NULL,
    ledger_created_at TIMESTAMPTZ NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (merchant_id, ledger_reference)
);


-- ────────────────────────────────────────────────────────────────────────────
-- 5. Immutability triggers — block UPDATE and DELETE on every partition.
--    Enforced on the partitioned parent; Postgres applies the trigger to
--    each partition automatically.
-- ────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION fn_immutable_merchant_ledger()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'merchant_ledger is append-only — cannot % rows. Post a reversing entry instead.',
        TG_OP
        USING ERRCODE = 'P0002';
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_immutable_merchant_ledger ON merchant_ledger;
CREATE TRIGGER trg_immutable_merchant_ledger
    BEFORE UPDATE OR DELETE ON merchant_ledger
    FOR EACH ROW
    EXECUTE FUNCTION fn_immutable_merchant_ledger();


-- ────────────────────────────────────────────────────────────────────────────
-- 6. Reference-number sequence (per-merchant counter inside posting fn)
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS merchant_ledger_seq (
    merchant_id        UUID    NOT NULL,
    yyyymm             CHAR(6) NOT NULL,
    last_seq           BIGINT  NOT NULL DEFAULT 0,
    PRIMARY KEY (merchant_id, yyyymm)
);


-- ────────────────────────────────────────────────────────────────────────────
-- 7. Posting function — THE ONLY supported way to write a ledger entry.
--
--    Atomic, idempotent, race-safe.
--
--    Returns the inserted (or pre-existing, on idempotency hit) row as JSONB.
-- ────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION fn_post_merchant_ledger_entry(
    p_merchant_id      UUID,
    p_branch_id        UUID,
    p_transaction_type merchant_ledger_txn_type,
    p_debit_amount     NUMERIC,
    p_credit_amount    NUMERIC,
    p_currency         CHAR(3) DEFAULT 'INR',
    p_source_type      TEXT    DEFAULT NULL,
    p_source_id        UUID    DEFAULT NULL,
    p_settlement_id    UUID    DEFAULT NULL,
    p_payment_id       UUID    DEFAULT NULL,
    p_order_id         UUID    DEFAULT NULL,
    p_bank_reference   TEXT    DEFAULT NULL,
    p_utr_number       TEXT    DEFAULT NULL,
    p_idempotency_key  TEXT    DEFAULT NULL,
    p_metadata         JSONB   DEFAULT '{}'::jsonb,
    p_created_by       UUID    DEFAULT NULL
) RETURNS JSONB AS $$
DECLARE
    v_currency   CHAR(3) := upper(p_currency);
    v_debit      NUMERIC(18,4) := COALESCE(p_debit_amount, 0);
    v_credit     NUMERIC(18,4) := COALESCE(p_credit_amount, 0);
    v_existing   merchant_ledger%ROWTYPE;
    v_prev_bal   NUMERIC(18,4);
    v_new_bal    NUMERIC(18,4);
    v_yyyymm     CHAR(6) := to_char(now() AT TIME ZONE 'UTC', 'YYYYMM');
    v_seq        BIGINT;
    v_ref        TEXT;
    v_id         UUID := gen_random_uuid();
    v_now        TIMESTAMPTZ := now();
    v_row        merchant_ledger%ROWTYPE;
BEGIN
    -- ── Validation ──────────────────────────────────────────────────────
    IF p_merchant_id IS NULL THEN
        RAISE EXCEPTION 'merchant_id is required';
    END IF;
    IF v_debit < 0 OR v_credit < 0 THEN
        RAISE EXCEPTION 'debit/credit must be non-negative';
    END IF;
    IF (v_debit > 0) = (v_credit > 0) THEN
        RAISE EXCEPTION 'exactly one of debit_amount / credit_amount must be > 0';
    END IF;

    -- ── Idempotency short-circuit (via companion uniqueness table) ───────
    IF p_idempotency_key IS NOT NULL THEN
        DECLARE
            v_existing_id UUID;
            v_existing_ts TIMESTAMPTZ;
        BEGIN
            SELECT ledger_id, ledger_created_at
              INTO v_existing_id, v_existing_ts
              FROM merchant_ledger_idempotency
             WHERE merchant_id     = p_merchant_id
               AND idempotency_key = p_idempotency_key;
            IF v_existing_id IS NOT NULL THEN
                SELECT * INTO v_existing
                  FROM merchant_ledger
                 WHERE id = v_existing_id AND created_at = v_existing_ts;
                IF FOUND THEN
                    RETURN to_jsonb(v_existing);
                END IF;
            END IF;
        END;
    END IF;

    -- ── Lock the per-(merchant,currency) balance row ────────────────────
    -- Insert-then-lock pattern: ensures the lock row exists, then takes
    -- a row lock that serialises concurrent posters for this merchant.
    INSERT INTO merchant_ledger_balance_locks (merchant_id, currency)
    VALUES (p_merchant_id, v_currency)
    ON CONFLICT (merchant_id, currency) DO NOTHING;

    SELECT current_balance INTO v_prev_bal
    FROM merchant_ledger_balance_locks
    WHERE merchant_id = p_merchant_id AND currency = v_currency
    FOR UPDATE;

    v_new_bal := v_prev_bal + v_credit - v_debit;

    -- ── Allocate per-merchant monthly sequence → ledger_reference ───────
    INSERT INTO merchant_ledger_seq (merchant_id, yyyymm, last_seq)
    VALUES (p_merchant_id, v_yyyymm, 1)
    ON CONFLICT (merchant_id, yyyymm) DO UPDATE
        SET last_seq = merchant_ledger_seq.last_seq + 1
    RETURNING last_seq INTO v_seq;

    v_ref := format('ML-%s-%s', v_yyyymm, lpad(v_seq::text, 8, '0'));

    -- ── Insert the immutable ledger row ─────────────────────────────────
    INSERT INTO merchant_ledger (
        id, merchant_id, branch_id, ledger_reference, transaction_type,
        debit_amount, credit_amount, balance_after, currency,
        source_type, source_id, settlement_id, payment_id, order_id,
        bank_reference, utr_number, idempotency_key, metadata,
        created_at, created_by
    ) VALUES (
        v_id, p_merchant_id, p_branch_id, v_ref, p_transaction_type,
        v_debit, v_credit, v_new_bal, v_currency,
        p_source_type, p_source_id, p_settlement_id, p_payment_id, p_order_id,
        p_bank_reference, p_utr_number, p_idempotency_key, COALESCE(p_metadata, '{}'::jsonb),
        v_now, p_created_by
    ) RETURNING * INTO v_row;
    -- ── Enforce per-merchant uniqueness via companion tables ───────────
    INSERT INTO merchant_ledger_references
        (merchant_id, ledger_reference, ledger_id, ledger_created_at)
    VALUES (p_merchant_id, v_ref, v_id, v_now);

    IF p_idempotency_key IS NOT NULL THEN
        INSERT INTO merchant_ledger_idempotency
            (merchant_id, idempotency_key, ledger_id, ledger_created_at)
        VALUES (p_merchant_id, p_idempotency_key, v_id, v_now);
    END IF;
    -- ── Update lock row with new running balance ────────────────────────
    UPDATE merchant_ledger_balance_locks
       SET current_balance = v_new_bal,
           last_entry_id   = v_id,
           last_posted_at  = v_now,
           version         = version + 1
     WHERE merchant_id = p_merchant_id AND currency = v_currency;

    RETURN to_jsonb(v_row);
END;
$$ LANGUAGE plpgsql;


-- ────────────────────────────────────────────────────────────────────────────
-- 8. Consistency check — recomputes balance from ledger sum, compares
--    against merchant_ledger_balance_locks.current_balance and the latest
--    balance_after on the ledger itself. Returns JSONB report.
-- ────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION fn_check_merchant_ledger_consistency(
    p_merchant_id UUID,
    p_currency    CHAR(3) DEFAULT 'INR'
) RETURNS JSONB AS $$
DECLARE
    v_currency       CHAR(3) := upper(p_currency);
    v_sum_balance    NUMERIC(18,4);
    v_lock_balance   NUMERIC(18,4);
    v_last_after     NUMERIC(18,4);
    v_entry_count    BIGINT;
BEGIN
    SELECT COALESCE(SUM(credit_amount - debit_amount), 0),
           COUNT(*)
      INTO v_sum_balance, v_entry_count
      FROM merchant_ledger
     WHERE merchant_id = p_merchant_id
       AND currency    = v_currency;

    SELECT current_balance INTO v_lock_balance
      FROM merchant_ledger_balance_locks
     WHERE merchant_id = p_merchant_id AND currency = v_currency;

    SELECT balance_after INTO v_last_after
      FROM merchant_ledger
     WHERE merchant_id = p_merchant_id AND currency = v_currency
     ORDER BY created_at DESC, ledger_reference DESC
     LIMIT 1;

    RETURN jsonb_build_object(
        'merchant_id',          p_merchant_id,
        'currency',             v_currency,
        'entry_count',          v_entry_count,
        'sum_of_movements',     v_sum_balance,
        'lock_balance',         COALESCE(v_lock_balance, 0),
        'last_balance_after',   COALESCE(v_last_after, 0),
        'lock_matches_sum',     COALESCE(v_lock_balance, 0) = v_sum_balance,
        'last_after_matches_sum', COALESCE(v_last_after, 0) = v_sum_balance,
        'checked_at',           now()
    );
END;
$$ LANGUAGE plpgsql STABLE;


-- ────────────────────────────────────────────────────────────────────────────
-- 9. RBAC — new permission keys
-- ────────────────────────────────────────────────────────────────────────────
INSERT INTO permissions (key) VALUES
    ('merchant_ledger.read'),
    ('merchant_ledger.write'),
    ('merchant_ledger.admin')
ON CONFLICT (key) DO NOTHING;

-- Owner: full. Manager: read+write. Cashier/Waiter/Staff: read only.
INSERT INTO role_permissions (role_id, permission_id, allowed, meta)
SELECT r.id, p.id, true, '{}'::jsonb
  FROM roles r
  JOIN permissions p ON p.key IN (
        'merchant_ledger.read', 'merchant_ledger.write', 'merchant_ledger.admin'
  )
 WHERE r.name = 'owner'
ON CONFLICT (role_id, permission_id) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id, allowed, meta)
SELECT r.id, p.id, true, '{}'::jsonb
  FROM roles r
  JOIN permissions p ON p.key IN ('merchant_ledger.read', 'merchant_ledger.write')
 WHERE r.name = 'manager'
ON CONFLICT (role_id, permission_id) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id, allowed, meta)
SELECT r.id, p.id, true, '{}'::jsonb
  FROM roles r
  JOIN permissions p ON p.key = 'merchant_ledger.read'
 WHERE r.name IN ('cashier', 'waiter', 'staff')
ON CONFLICT (role_id, permission_id) DO NOTHING;

COMMIT;
