-- 063_geofence_and_saas_invoices.sql
--
-- Adds:
--   1. Geo-fence columns on sub_branches (lat/lng/radius) + haversine helper.
--   2. SaaS-invoice ledger so Bittu->Merchant monthly invoices are durable
--      (a PDF is generated on the fly; the row makes it idempotent and
--      auditable per merchant per period).
--
-- Idempotent: safe to run twice.

BEGIN;

-- ───────────────────────────── 1. Geo-fence on branches ─────────────────────────────
ALTER TABLE sub_branches
    ADD COLUMN IF NOT EXISTS latitude               NUMERIC(10, 8),
    ADD COLUMN IF NOT EXISTS longitude              NUMERIC(11, 8),
    ADD COLUMN IF NOT EXISTS geofence_radius_meters INTEGER NOT NULL DEFAULT 100,
    ADD COLUMN IF NOT EXISTS geofence_enabled       BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN sub_branches.latitude  IS 'Branch GPS latitude (WGS84). NULL ⇒ geofence skipped.';
COMMENT ON COLUMN sub_branches.longitude IS 'Branch GPS longitude (WGS84). NULL ⇒ geofence skipped.';
COMMENT ON COLUMN sub_branches.geofence_radius_meters IS 'Max allowed distance in meters from branch GPS for /orders/checkout & /payments/initiate (default 100m).';
COMMENT ON COLUMN sub_branches.geofence_enabled IS 'Per-branch toggle. When false, geofence is skipped even if lat/lng present.';

-- Haversine distance helper (meters). Returns NULL if any input is NULL.
CREATE OR REPLACE FUNCTION fn_haversine_meters(
    lat1 NUMERIC, lng1 NUMERIC,
    lat2 NUMERIC, lng2 NUMERIC
) RETURNS DOUBLE PRECISION
LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE AS $$
DECLARE
    r        CONSTANT DOUBLE PRECISION := 6371000.0; -- Earth radius (m)
    phi1     DOUBLE PRECISION;
    phi2     DOUBLE PRECISION;
    dphi     DOUBLE PRECISION;
    dlambda  DOUBLE PRECISION;
    a        DOUBLE PRECISION;
BEGIN
    IF lat1 IS NULL OR lng1 IS NULL OR lat2 IS NULL OR lng2 IS NULL THEN
        RETURN NULL;
    END IF;
    phi1    := radians(lat1::double precision);
    phi2    := radians(lat2::double precision);
    dphi    := radians((lat2 - lat1)::double precision);
    dlambda := radians((lng2 - lng1)::double precision);
    a := sin(dphi / 2) * sin(dphi / 2)
       + cos(phi1) * cos(phi2) * sin(dlambda / 2) * sin(dlambda / 2);
    RETURN 2 * r * atan2(sqrt(a), sqrt(1 - a));
END;
$$;

COMMENT ON FUNCTION fn_haversine_meters IS 'Great-circle distance (meters) between two WGS84 points. NULL-safe.';

-- ───────────────────────────── 2. SaaS-invoice ledger ─────────────────────────────
CREATE TABLE IF NOT EXISTS bittu_saas_invoices (
    id                  BIGSERIAL PRIMARY KEY,
    invoice_number      TEXT      NOT NULL,
    merchant_id         UUID      NOT NULL,
    period_year         INTEGER   NOT NULL,
    period_month        INTEGER   NOT NULL CHECK (period_month BETWEEN 1 AND 12),
    currency            CHAR(3)   NOT NULL DEFAULT 'INR',
    gross_collected     NUMERIC(14, 2) NOT NULL DEFAULT 0,
    bittu_fee_amount    NUMERIC(14, 2) NOT NULL DEFAULT 0,
    gst_on_fee_amount   NUMERIC(14, 2) NOT NULL DEFAULT 0,
    total_payable       NUMERIC(14, 2) NOT NULL DEFAULT 0,
    txn_count           INTEGER   NOT NULL DEFAULT 0,
    status              TEXT      NOT NULL DEFAULT 'issued'
                          CHECK (status IN ('draft', 'issued', 'paid', 'void')),
    issued_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    paid_at             TIMESTAMPTZ,
    voided_at           TIMESTAMPTZ,
    metadata            JSONB     NOT NULL DEFAULT '{}'::jsonb,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_bittu_saas_invoices_period UNIQUE (merchant_id, period_year, period_month),
    CONSTRAINT uq_bittu_saas_invoices_number UNIQUE (invoice_number)
);

CREATE INDEX IF NOT EXISTS ix_bittu_saas_invoices_merchant
    ON bittu_saas_invoices (merchant_id, period_year DESC, period_month DESC);

COMMENT ON TABLE bittu_saas_invoices IS
    'Per-merchant per-month SaaS invoice (Bittu platform fee + GST). Auto-generated by the merchant-reports endpoint. UNIQUE per (merchant_id, year, month) — idempotent issuance.';

COMMIT;
